# Generated by Django 4.2.7 on 2023-11-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('codigo_produto', models.CharField(max_length=200)),
                ('quatidade_inicial', models.BigIntegerField(default=0)),
                ('quantidade_minima', models.BigIntegerField(default=0)),
                ('preco', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.categoria')),
            ],
        ),
    ]
