# Generated by Django 4.2.7 on 2023-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0002_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_custo',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
