# Generated by Django 4.2.7 on 2023-11-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0005_rename_nome_do_produto_produto_nome_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quatidade_inicial',
            new_name='quatidade',
        ),
    ]
