# Generated by Django 4.2.7 on 2023-11-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0006_rename_quatidade_inicial_produto_quatidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quatidade',
            new_name='quantidade',
        ),
    ]
